package com.example.Robomain.domain.purchase_request.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Date;
import java.util.UUID;

import com.example.Robomain.domain.shared.enums.EnumPRStatus;
import com.example.Robomain.domain.shared.enums.EnumPRType;
import com.example.Robomain.domain.shared.exception.ValidationException;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * PurchaseRequest domain entity — a request to procure inventory items.
 * Lifecycle: PENDING → APPROVED | REJECTED.
 * Can be created manually or auto-generated by low-stock events.
 */
@Getter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class PurchaseRequest {

    private UUID id;
    private String requestCode;
    private UUID inventoryId;
    private int requestedQuantity;
    private BigDecimal estimatedCost;
    @Builder.Default
    private EnumPRStatus status = EnumPRStatus.PENDING;
    @Builder.Default
    private EnumPRType type = EnumPRType.MANUAL;
    private String reason;
    private UUID requestedBy;
    private LocalDate requestedDate;
    private LocalDate requiredDate;
    private UUID approvedBy;
    private LocalDate approvedDate;
    private String approvalNotes;
    private UUID vendorId;
    private UUID enterpriseId;
    private Date createdAt;
    private Date updatedAt;

    public static PurchaseRequest create(String requestCode, UUID inventoryId, int requestedQuantity,
                                          BigDecimal estimatedCost, UUID requestedBy, UUID enterpriseId) {
        if (requestCode == null || requestCode.isBlank()) throw new ValidationException("Request code cannot be blank");
        if (inventoryId == null) throw new ValidationException("Inventory is required");
        if (requestedQuantity <= 0) throw new ValidationException("Requested quantity must be positive");
        if (enterpriseId == null) throw new ValidationException("Enterprise is required");
        return PurchaseRequest.builder()
                .id(UUID.randomUUID())
                .requestCode(requestCode).inventoryId(inventoryId)
                .requestedQuantity(requestedQuantity).estimatedCost(estimatedCost)
                .status(EnumPRStatus.PENDING).type(EnumPRType.MANUAL)
                .requestedBy(requestedBy).requestedDate(LocalDate.now())
                .enterpriseId(enterpriseId)
                .build();
    }

    /** Approves the request. Only valid from PENDING status. */
    public void approve(UUID approvedBy, String approvalNotes) {
        if (this.status != EnumPRStatus.PENDING) {
            throw new ValidationException("Can only approve a PENDING purchase request, current: " + this.status);
        }
        this.status = EnumPRStatus.APPROVED;
        this.approvedBy = approvedBy;
        this.approvedDate = LocalDate.now();
        this.approvalNotes = approvalNotes;
    }

    /** Rejects the request. Only valid from PENDING status. */
    public void reject(String reason) {
        if (this.status != EnumPRStatus.PENDING) {
            throw new ValidationException("Can only reject a PENDING purchase request, current: " + this.status);
        }
        this.status = EnumPRStatus.REJECTED;
        this.reason = reason;
    }

    public void assignVendor(UUID vendorId) { this.vendorId = vendorId; }

    public void setRequiredDate(LocalDate requiredDate) { this.requiredDate = requiredDate; }
}
