ALTER TABLE if EXISTS tool
ADD COLUMN IF NOT EXISTS file_info JSONB;

ALTER TABLE if EXISTS equipment
ADD COLUMN IF NOT EXISTS file_info JSONB;

ALTER TABLE if EXISTS facility_location
ADD COLUMN IF NOT EXISTS file_info JSONB;